### ISSUE TITLE
micehide is not working correctly and various suggestions

### ISSUE THREAD

**Issue by jhx0** [rilysh/micehide#1]
Hi @rilysh!

Maybe i'm not handling the program the right way, but it seems that the mouse pointer newer dissapears. I tried running with different arguments (**-t 2000**, **-t -w 4000**, etc.) but in the end i could see that the the case KeyPress was never hit during my testing (I've added some simple printf() statements to debug).
In general i get the **"OK: Active"** output, which is before the for loope enters.

Also, i saw that:
```C
Window root = DefaultRootWindow(dpy);
```
was assigned but never used. A coule lines down i saw this:
```C
if (wait != 0) {
                XFixesHideCursor(dpy, DefaultRootWindow(dpy));
                ...       
            }
            XFixesHideCursor(dpy, DefaultRootWindow(dpy));
            ...
            XFixesShowCursor(dpy, DefaultRootWindow(dpy));
            ...
```
I think these should make use of the before assigned "root" variable.
This was uncovered with additional compiler flags:
```
-Wall -Wunused -Wextra -pedantic -Werror
```
The Makefile also does not create a micehide binary since the default naming will be "a.out".
This could be fixed as follows:
```Make
...
LIBS=-lX11 -lXfixes
BIN=micehide

all:
	$(CC) $(FLAGS) $(PROGRAM).c $(LIBS) -o $(BIN)
...
```
The last thing that could be improved is:
```C
static void show_and_hide(unsigned int ms, int wait)
{
    if (ms < 0) {
```
Since **ms** is **unsigned** the check can never be less than zero. Changing **ms** to simply int would solve the issue given here. (Uncovered with more strict compiler flags under GCC)

**Tested on:**
Debian 11 (amd64) Bullseye with GCC. GCC information:
```Shell
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)
```

**Comment by rilysh** [comment]
Hello!  Thank you for pointing out the issues. I completely didn't notice that I used `sleep` instead `usleep` and in doing so probably some wrong values got passed through `sleep`.
Some other things I forgot to place, `root` which I was planning to use as a function variable of `DefaultRootWindow`  but forgot and instead applied the function directly...

I have pushed some changes, this time it should be fixed. Also for `-w` parameter, it will be something like this (`./micehide -w -t 5000`) where it waits for a key press and then starts the timer to wait for the given time (given time after `-t [time]`.)

There's another issue, I didn't notice earlier is that some gtk windows doesn't being focused through `XGetInputFocus` and thus can't be selected with `XSelectInput`. Sometimes for this, it returns X11 returns `BadWindow` error.  `xinput 2` seems fixed that, however, it requires manual implementation and I'm new to X11 API (just started with this program).

In time you may also try xbanish (https://github.com/jcs/xbanish). There's already an implementation for xinput 2 https://github.com/jcs/xbanish/blob/189ce79b1df4eb4995980530ebc3d28715a67488/xbanish.c#L409 to fix the previous issue.

**Comment by jhx0** [comment]
Thanks for the work you did @rilysh!

I currently run Xfce - which is GTK based... which is why there are issues, like you explained.
(I supected GTK to be a issue here since raw X11 is used)

The changes compile fine, no problem here. (Just tested it on my system)

I will close the issue, since for the the issues are resolved.
Will check out xbanish.

Thanks @rilysh :)
